In [2]:
with open('sentences.txt') as file:
    sentences = file.read().splitlines()

In [3]:
import re

In [4]:
splitted = [re.split('[^a-z]+', sentence.lower()) for sentence in sentences]

In [30]:
cleaned = []
words = []
for element in splitted:
    filtered = list(filter(bool, element))
    cleaned.append(filtered)
    words.extend(filtered)

words = list(set(words))

In [6]:
from collections import Counter

In [25]:
n = len(sentences)
d = len(words)
print(n, d)

22 254


In [17]:
counted = [Counter(x) for x in cleaned]

In [9]:
import numpy as np
from scipy.spatial import distance

In [10]:
a = np.zeros((n, d))

In [31]:
for i in range(n):
    for j in range(d):
        a[i][j] = counted[i][words[j]]

print(a)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
dists = [distance.cosine(a[0], a[k]) for k in range(1, n)]
print(*dists, sep='\n')

0.9527544408738466
0.8644738145642124
0.8951715163278082
0.7770887149698589
0.9402385695332803
0.7327387580875756
0.9258750683338899
0.8842724875284311
0.9055088817476932
0.8328165362273942
0.8804771390665607
0.8396432548525454
0.8703592552895671
0.8740118423302576
0.9442721787424647
0.8406361854220809
0.956644501523794
0.9442721787424647
0.8885443574849294
0.8427572744917122
0.8250364469440588


In [33]:
i1, i2 = np.argsort(dists)[:2]
print(i1 + 1, dists[i1], sentences[i1 + 1])
print(i2 + 1, dists[i2], sentences[i2 + 1])

6 0.7327387580875756 Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).
4 0.7770887149698589 In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.
